// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: house.proto

package com.example.mq_protocol.dynamic_protocol;

public final class Housepro {
  private Housepro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HouseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:House)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string xiaoqu = 1;</code>
     * @return The xiaoqu.
     */
    String getXiaoqu();
    /**
     * <code>string xiaoqu = 1;</code>
     * @return The bytes for xiaoqu.
     */
    com.google.protobuf.ByteString
        getXiaoquBytes();

    /**
     * <code>string lou = 2;</code>
     * @return The lou.
     */
    String getLou();
    /**
     * <code>string lou = 2;</code>
     * @return The bytes for lou.
     */
    com.google.protobuf.ByteString
        getLouBytes();

    /**
     * <code>int64 danyuan = 3;</code>
     * @return The danyuan.
     */
    long getDanyuan();
  }
  /**
   * Protobuf type {@code House}
   */
  public static final class House extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:House)
      HouseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use House.newBuilder() to construct.
    private House(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private House() {
      xiaoqu_ = "";
      lou_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new House();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private House(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              xiaoqu_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              lou_ = s;
              break;
            }
            case 24: {

              danyuan_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Housepro.internal_static_House_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Housepro.internal_static_House_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              House.class, Builder.class);
    }

    public static final int XIAOQU_FIELD_NUMBER = 1;
    private volatile Object xiaoqu_;
    /**
     * <code>string xiaoqu = 1;</code>
     * @return The xiaoqu.
     */
    @Override
    public String getXiaoqu() {
      Object ref = xiaoqu_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        xiaoqu_ = s;
        return s;
      }
    }
    /**
     * <code>string xiaoqu = 1;</code>
     * @return The bytes for xiaoqu.
     */
    @Override
    public com.google.protobuf.ByteString
        getXiaoquBytes() {
      Object ref = xiaoqu_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        xiaoqu_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOU_FIELD_NUMBER = 2;
    private volatile Object lou_;
    /**
     * <code>string lou = 2;</code>
     * @return The lou.
     */
    @Override
    public String getLou() {
      Object ref = lou_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lou_ = s;
        return s;
      }
    }
    /**
     * <code>string lou = 2;</code>
     * @return The bytes for lou.
     */
    @Override
    public com.google.protobuf.ByteString
        getLouBytes() {
      Object ref = lou_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lou_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DANYUAN_FIELD_NUMBER = 3;
    private long danyuan_;
    /**
     * <code>int64 danyuan = 3;</code>
     * @return The danyuan.
     */
    @Override
    public long getDanyuan() {
      return danyuan_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getXiaoquBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, xiaoqu_);
      }
      if (!getLouBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lou_);
      }
      if (danyuan_ != 0L) {
        output.writeInt64(3, danyuan_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getXiaoquBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, xiaoqu_);
      }
      if (!getLouBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lou_);
      }
      if (danyuan_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, danyuan_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof House)) {
        return super.equals(obj);
      }
      House other = (House) obj;

      if (!getXiaoqu()
          .equals(other.getXiaoqu())) return false;
      if (!getLou()
          .equals(other.getLou())) return false;
      if (getDanyuan()
          != other.getDanyuan()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + XIAOQU_FIELD_NUMBER;
      hash = (53 * hash) + getXiaoqu().hashCode();
      hash = (37 * hash) + LOU_FIELD_NUMBER;
      hash = (53 * hash) + getLou().hashCode();
      hash = (37 * hash) + DANYUAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDanyuan());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static House parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static House parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static House parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static House parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static House parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static House parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static House parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static House parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static House parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static House parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static House parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static House parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(House prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code House}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:House)
        HouseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Housepro.internal_static_House_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Housepro.internal_static_House_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                House.class, Builder.class);
      }

      // Construct using com.example.mq_protocol.dynamic_protocol.Housepro.House.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        xiaoqu_ = "";

        lou_ = "";

        danyuan_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Housepro.internal_static_House_descriptor;
      }

      @Override
      public House getDefaultInstanceForType() {
        return House.getDefaultInstance();
      }

      @Override
      public House build() {
        House result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public House buildPartial() {
        House result = new House(this);
        result.xiaoqu_ = xiaoqu_;
        result.lou_ = lou_;
        result.danyuan_ = danyuan_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof House) {
          return mergeFrom((House)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(House other) {
        if (other == House.getDefaultInstance()) return this;
        if (!other.getXiaoqu().isEmpty()) {
          xiaoqu_ = other.xiaoqu_;
          onChanged();
        }
        if (!other.getLou().isEmpty()) {
          lou_ = other.lou_;
          onChanged();
        }
        if (other.getDanyuan() != 0L) {
          setDanyuan(other.getDanyuan());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        House parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (House) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object xiaoqu_ = "";
      /**
       * <code>string xiaoqu = 1;</code>
       * @return The xiaoqu.
       */
      public String getXiaoqu() {
        Object ref = xiaoqu_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          xiaoqu_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string xiaoqu = 1;</code>
       * @return The bytes for xiaoqu.
       */
      public com.google.protobuf.ByteString
          getXiaoquBytes() {
        Object ref = xiaoqu_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          xiaoqu_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string xiaoqu = 1;</code>
       * @param value The xiaoqu to set.
       * @return This builder for chaining.
       */
      public Builder setXiaoqu(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        xiaoqu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string xiaoqu = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearXiaoqu() {
        
        xiaoqu_ = getDefaultInstance().getXiaoqu();
        onChanged();
        return this;
      }
      /**
       * <code>string xiaoqu = 1;</code>
       * @param value The bytes for xiaoqu to set.
       * @return This builder for chaining.
       */
      public Builder setXiaoquBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        xiaoqu_ = value;
        onChanged();
        return this;
      }

      private Object lou_ = "";
      /**
       * <code>string lou = 2;</code>
       * @return The lou.
       */
      public String getLou() {
        Object ref = lou_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          lou_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string lou = 2;</code>
       * @return The bytes for lou.
       */
      public com.google.protobuf.ByteString
          getLouBytes() {
        Object ref = lou_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          lou_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lou = 2;</code>
       * @param value The lou to set.
       * @return This builder for chaining.
       */
      public Builder setLou(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lou_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lou = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLou() {
        
        lou_ = getDefaultInstance().getLou();
        onChanged();
        return this;
      }
      /**
       * <code>string lou = 2;</code>
       * @param value The bytes for lou to set.
       * @return This builder for chaining.
       */
      public Builder setLouBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lou_ = value;
        onChanged();
        return this;
      }

      private long danyuan_ ;
      /**
       * <code>int64 danyuan = 3;</code>
       * @return The danyuan.
       */
      @Override
      public long getDanyuan() {
        return danyuan_;
      }
      /**
       * <code>int64 danyuan = 3;</code>
       * @param value The danyuan to set.
       * @return This builder for chaining.
       */
      public Builder setDanyuan(long value) {
        
        danyuan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 danyuan = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDanyuan() {
        
        danyuan_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:House)
    }

    // @@protoc_insertion_point(class_scope:House)
    private static final House DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new House();
    }

    public static House getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<House>
        PARSER = new com.google.protobuf.AbstractParser<House>() {
      @Override
      public House parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new House(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<House> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<House> getParserForType() {
      return PARSER;
    }

    @Override
    public House getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_House_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_House_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013house.proto\"5\n\005House\022\016\n\006xiaoqu\030\001 \001(\t\022\013" +
      "\n\003lou\030\002 \001(\t\022\017\n\007danyuan\030\003 \001(\003B4\n(com.exam" +
      "ple.mq_protocol.dynamic_protocolB\010Housep" +
      "rob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_House_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_House_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_House_descriptor,
        new String[] { "Xiaoqu", "Lou", "Danyuan", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
