// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dynamic.proto
package com.example.mq_protocol.dynamic_protocol;
public final class Ownerpro {
  private Ownerpro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OwnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Owner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string phone = 2;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 2;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>int64 age = 3;</code>
     * @return The age.
     */
    long getAge();

    /**
     * <code>repeated .House houses = 4;</code>
     */
    java.util.List<com.example.mq_protocol.dynamic_protocol.Housepro.House> 
        getHousesList();
    /**
     * <code>repeated .House houses = 4;</code>
     */
    com.example.mq_protocol.dynamic_protocol.Housepro.House getHouses(int index);
    /**
     * <code>repeated .House houses = 4;</code>
     */
    int getHousesCount();
    /**
     * <code>repeated .House houses = 4;</code>
     */
    java.util.List<? extends com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder> 
        getHousesOrBuilderList();
    /**
     * <code>repeated .House houses = 4;</code>
     */
    com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder getHousesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Owner}
   */
  public static final class Owner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Owner)
      OwnerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Owner.newBuilder() to construct.
    private Owner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Owner() {
      name_ = "";
      phone_ = "";
      houses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Owner();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Owner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                houses_ = new java.util.ArrayList<com.example.mq_protocol.dynamic_protocol.Housepro.House>();
                mutable_bitField0_ |= 0x00000001;
              }
              houses_.add(
                  input.readMessage(com.example.mq_protocol.dynamic_protocol.Housepro.House.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          houses_ = java.util.Collections.unmodifiableList(houses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Ownerpro.internal_static_Owner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Ownerpro.internal_static_Owner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Ownerpro.Owner.class, Ownerpro.Owner.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 2;
    private volatile java.lang.Object phone_;
    /**
     * <code>string phone = 2;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 2;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private long age_;
    /**
     * <code>int64 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public long getAge() {
      return age_;
    }

    public static final int HOUSES_FIELD_NUMBER = 4;
    private java.util.List<com.example.mq_protocol.dynamic_protocol.Housepro.House> houses_;
    /**
     * <code>repeated .House houses = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.mq_protocol.dynamic_protocol.Housepro.House> getHousesList() {
      return houses_;
    }
    /**
     * <code>repeated .House houses = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder> 
        getHousesOrBuilderList() {
      return houses_;
    }
    /**
     * <code>repeated .House houses = 4;</code>
     */
    @java.lang.Override
    public int getHousesCount() {
      return houses_.size();
    }
    /**
     * <code>repeated .House houses = 4;</code>
     */
    @java.lang.Override
    public com.example.mq_protocol.dynamic_protocol.Housepro.House getHouses(int index) {
      return houses_.get(index);
    }
    /**
     * <code>repeated .House houses = 4;</code>
     */
    @java.lang.Override
    public com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder getHousesOrBuilder(
        int index) {
      return houses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phone_);
      }
      if (age_ != 0L) {
        output.writeInt64(3, age_);
      }
      for (int i = 0; i < houses_.size(); i++) {
        output.writeMessage(4, houses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phone_);
      }
      if (age_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, age_);
      }
      for (int i = 0; i < houses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, houses_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Ownerpro.Owner)) {
        return super.equals(obj);
      }
      Ownerpro.Owner other = (Ownerpro.Owner) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getHousesList()
          .equals(other.getHousesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAge());
      if (getHousesCount() > 0) {
        hash = (37 * hash) + HOUSES_FIELD_NUMBER;
        hash = (53 * hash) + getHousesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Ownerpro.Owner parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ownerpro.Owner parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ownerpro.Owner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ownerpro.Owner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ownerpro.Owner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Ownerpro.Owner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Ownerpro.Owner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Ownerpro.Owner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ownerpro.Owner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Ownerpro.Owner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Ownerpro.Owner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Ownerpro.Owner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Ownerpro.Owner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Owner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Owner)
        Ownerpro.OwnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Ownerpro.internal_static_Owner_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Ownerpro.internal_static_Owner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Ownerpro.Owner.class, Ownerpro.Owner.Builder.class);
      }

      // Construct using Ownerpro.Owner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHousesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        phone_ = "";

        age_ = 0L;

        if (housesBuilder_ == null) {
          houses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          housesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Ownerpro.internal_static_Owner_descriptor;
      }

      @java.lang.Override
      public Ownerpro.Owner getDefaultInstanceForType() {
        return Ownerpro.Owner.getDefaultInstance();
      }

      @java.lang.Override
      public Ownerpro.Owner build() {
        Ownerpro.Owner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Ownerpro.Owner buildPartial() {
        Ownerpro.Owner result = new Ownerpro.Owner(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.phone_ = phone_;
        result.age_ = age_;
        if (housesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            houses_ = java.util.Collections.unmodifiableList(houses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.houses_ = houses_;
        } else {
          result.houses_ = housesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Ownerpro.Owner) {
          return mergeFrom((Ownerpro.Owner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Ownerpro.Owner other) {
        if (other == Ownerpro.Owner.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (other.getAge() != 0L) {
          setAge(other.getAge());
        }
        if (housesBuilder_ == null) {
          if (!other.houses_.isEmpty()) {
            if (houses_.isEmpty()) {
              houses_ = other.houses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHousesIsMutable();
              houses_.addAll(other.houses_);
            }
            onChanged();
          }
        } else {
          if (!other.houses_.isEmpty()) {
            if (housesBuilder_.isEmpty()) {
              housesBuilder_.dispose();
              housesBuilder_ = null;
              houses_ = other.houses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              housesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHousesFieldBuilder() : null;
            } else {
              housesBuilder_.addAllMessages(other.houses_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Ownerpro.Owner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Ownerpro.Owner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 2;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 2;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 2;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 2;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private long age_ ;
      /**
       * <code>int64 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public long getAge() {
        return age_;
      }
      /**
       * <code>int64 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(long value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.example.mq_protocol.dynamic_protocol.Housepro.House> houses_ =
        java.util.Collections.emptyList();
      private void ensureHousesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          houses_ = new java.util.ArrayList<com.example.mq_protocol.dynamic_protocol.Housepro.House>(houses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.mq_protocol.dynamic_protocol.Housepro.House, com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder, com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder> housesBuilder_;

      /**
       * <code>repeated .House houses = 4;</code>
       */
      public java.util.List<com.example.mq_protocol.dynamic_protocol.Housepro.House> getHousesList() {
        if (housesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(houses_);
        } else {
          return housesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public int getHousesCount() {
        if (housesBuilder_ == null) {
          return houses_.size();
        } else {
          return housesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public com.example.mq_protocol.dynamic_protocol.Housepro.House getHouses(int index) {
        if (housesBuilder_ == null) {
          return houses_.get(index);
        } else {
          return housesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder setHouses(
          int index, com.example.mq_protocol.dynamic_protocol.Housepro.House value) {
        if (housesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHousesIsMutable();
          houses_.set(index, value);
          onChanged();
        } else {
          housesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder setHouses(
          int index, com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder builderForValue) {
        if (housesBuilder_ == null) {
          ensureHousesIsMutable();
          houses_.set(index, builderForValue.build());
          onChanged();
        } else {
          housesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder addHouses(com.example.mq_protocol.dynamic_protocol.Housepro.House value) {
        if (housesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHousesIsMutable();
          houses_.add(value);
          onChanged();
        } else {
          housesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder addHouses(
          int index, com.example.mq_protocol.dynamic_protocol.Housepro.House value) {
        if (housesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHousesIsMutable();
          houses_.add(index, value);
          onChanged();
        } else {
          housesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder addHouses(
          com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder builderForValue) {
        if (housesBuilder_ == null) {
          ensureHousesIsMutable();
          houses_.add(builderForValue.build());
          onChanged();
        } else {
          housesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder addHouses(
          int index, com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder builderForValue) {
        if (housesBuilder_ == null) {
          ensureHousesIsMutable();
          houses_.add(index, builderForValue.build());
          onChanged();
        } else {
          housesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder addAllHouses(
          java.lang.Iterable<? extends com.example.mq_protocol.dynamic_protocol.Housepro.House> values) {
        if (housesBuilder_ == null) {
          ensureHousesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, houses_);
          onChanged();
        } else {
          housesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder clearHouses() {
        if (housesBuilder_ == null) {
          houses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          housesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public Builder removeHouses(int index) {
        if (housesBuilder_ == null) {
          ensureHousesIsMutable();
          houses_.remove(index);
          onChanged();
        } else {
          housesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder getHousesBuilder(
          int index) {
        return getHousesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder getHousesOrBuilder(
          int index) {
        if (housesBuilder_ == null) {
          return houses_.get(index);  } else {
          return housesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public java.util.List<? extends com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder> 
           getHousesOrBuilderList() {
        if (housesBuilder_ != null) {
          return housesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(houses_);
        }
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder addHousesBuilder() {
        return getHousesFieldBuilder().addBuilder(
            com.example.mq_protocol.dynamic_protocol.Housepro.House.getDefaultInstance());
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder addHousesBuilder(
          int index) {
        return getHousesFieldBuilder().addBuilder(
            index, com.example.mq_protocol.dynamic_protocol.Housepro.House.getDefaultInstance());
      }
      /**
       * <code>repeated .House houses = 4;</code>
       */
      public java.util.List<com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder> 
           getHousesBuilderList() {
        return getHousesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.mq_protocol.dynamic_protocol.Housepro.House, com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder, com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder> 
          getHousesFieldBuilder() {
        if (housesBuilder_ == null) {
          housesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.mq_protocol.dynamic_protocol.Housepro.House, com.example.mq_protocol.dynamic_protocol.Housepro.House.Builder, com.example.mq_protocol.dynamic_protocol.Housepro.HouseOrBuilder>(
                  houses_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          houses_ = null;
        }
        return housesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Owner)
    }

    // @@protoc_insertion_point(class_scope:Owner)
    private static final Ownerpro.Owner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Ownerpro.Owner();
    }

    public static Ownerpro.Owner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Owner>
        PARSER = new com.google.protobuf.AbstractParser<Owner>() {
      @java.lang.Override
      public Owner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Owner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Owner> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Owner> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Ownerpro.Owner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Owner_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Owner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdynamic.proto\032\013house.proto\"I\n\005Owner\022\014\n" +
      "\004name\030\001 \001(\t\022\r\n\005phone\030\002 \001(\t\022\013\n\003age\030\003 \001(\003\022" +
      "\026\n\006houses\030\004 \003(\0132\006.HouseB\nB\010Ownerprob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.mq_protocol.dynamic_protocol.Housepro.getDescriptor(),
        });
    internal_static_Owner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Owner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Owner_descriptor,
        new java.lang.String[] { "Name", "Phone", "Age", "Houses", });
    com.example.mq_protocol.dynamic_protocol.Housepro.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
