// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: self_describe.proto
package com.example.mq_protocol.dynamic_protocol;
public final class SelfDescribePro {
  private SelfDescribePro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SelfDescribeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SelfDescribe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return Whether the descriptorSet field is set.
     */
    boolean hasDescriptorSet();
    /**
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return The descriptorSet.
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet();
    /**
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bytes message = 3;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code SelfDescribe}
   */
  public static final class SelfDescribe extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SelfDescribe)
      SelfDescribeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SelfDescribe.newBuilder() to construct.
    private SelfDescribe(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SelfDescribe() {
      name_ = "";
      message_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SelfDescribe();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SelfDescribe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder subBuilder = null;
              if (descriptorSet_ != null) {
                subBuilder = descriptorSet_.toBuilder();
              }
              descriptorSet_ = input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorSet.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(descriptorSet_);
                descriptorSet_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {

              message_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SelfDescribePro.internal_static_SelfDescribe_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SelfDescribePro.internal_static_SelfDescribe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SelfDescribePro.SelfDescribe.class, SelfDescribePro.SelfDescribe.Builder.class);
    }

    public static final int DESCRIPTOR_SET_FIELD_NUMBER = 1;
    private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorSet_;
    /**
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return Whether the descriptorSet field is set.
     */
    @java.lang.Override
    public boolean hasDescriptorSet() {
      return descriptorSet_ != null;
    }
    /**
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return The descriptorSet.
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet() {
      return descriptorSet_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
    }
    /**
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder() {
      return getDescriptorSet();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>bytes message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasDescriptorSet()) {
        if (!getDescriptorSet().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (descriptorSet_ != null) {
        output.writeMessage(1, getDescriptorSet());
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!message_.isEmpty()) {
        output.writeBytes(3, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (descriptorSet_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDescriptorSet());
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SelfDescribePro.SelfDescribe)) {
        return super.equals(obj);
      }
      SelfDescribePro.SelfDescribe other = (SelfDescribePro.SelfDescribe) obj;

      if (hasDescriptorSet() != other.hasDescriptorSet()) return false;
      if (hasDescriptorSet()) {
        if (!getDescriptorSet()
            .equals(other.getDescriptorSet())) return false;
      }
      if (!getName()
          .equals(other.getName())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDescriptorSet()) {
        hash = (37 * hash) + DESCRIPTOR_SET_FIELD_NUMBER;
        hash = (53 * hash) + getDescriptorSet().hashCode();
      }
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SelfDescribePro.SelfDescribe parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SelfDescribePro.SelfDescribe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SelfDescribePro.SelfDescribe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SelfDescribePro.SelfDescribe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SelfDescribePro.SelfDescribe prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SelfDescribe}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SelfDescribe)
        SelfDescribePro.SelfDescribeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SelfDescribePro.internal_static_SelfDescribe_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SelfDescribePro.internal_static_SelfDescribe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SelfDescribePro.SelfDescribe.class, SelfDescribePro.SelfDescribe.Builder.class);
      }

      // Construct using SelfDescribePro.SelfDescribe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = null;
        } else {
          descriptorSet_ = null;
          descriptorSetBuilder_ = null;
        }
        name_ = "";

        message_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SelfDescribePro.internal_static_SelfDescribe_descriptor;
      }

      @java.lang.Override
      public SelfDescribePro.SelfDescribe getDefaultInstanceForType() {
        return SelfDescribePro.SelfDescribe.getDefaultInstance();
      }

      @java.lang.Override
      public SelfDescribePro.SelfDescribe build() {
        SelfDescribePro.SelfDescribe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SelfDescribePro.SelfDescribe buildPartial() {
        SelfDescribePro.SelfDescribe result = new SelfDescribePro.SelfDescribe(this);
        if (descriptorSetBuilder_ == null) {
          result.descriptorSet_ = descriptorSet_;
        } else {
          result.descriptorSet_ = descriptorSetBuilder_.build();
        }
        result.name_ = name_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SelfDescribePro.SelfDescribe) {
          return mergeFrom((SelfDescribePro.SelfDescribe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SelfDescribePro.SelfDescribe other) {
        if (other == SelfDescribePro.SelfDescribe.getDefaultInstance()) return this;
        if (other.hasDescriptorSet()) {
          mergeDescriptorSet(other.getDescriptorSet());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasDescriptorSet()) {
          if (!getDescriptorSet().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SelfDescribePro.SelfDescribe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SelfDescribePro.SelfDescribe) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorSet_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> descriptorSetBuilder_;
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       * @return Whether the descriptorSet field is set.
       */
      public boolean hasDescriptorSet() {
        return descriptorSetBuilder_ != null || descriptorSet_ != null;
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       * @return The descriptorSet.
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet() {
        if (descriptorSetBuilder_ == null) {
          return descriptorSet_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
        } else {
          return descriptorSetBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder setDescriptorSet(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          descriptorSet_ = value;
          onChanged();
        } else {
          descriptorSetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder setDescriptorSet(
          com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder builderForValue) {
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = builderForValue.build();
          onChanged();
        } else {
          descriptorSetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder mergeDescriptorSet(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorSetBuilder_ == null) {
          if (descriptorSet_ != null) {
            descriptorSet_ =
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.newBuilder(descriptorSet_).mergeFrom(value).buildPartial();
          } else {
            descriptorSet_ = value;
          }
          onChanged();
        } else {
          descriptorSetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder clearDescriptorSet() {
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = null;
          onChanged();
        } else {
          descriptorSet_ = null;
          descriptorSetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder getDescriptorSetBuilder() {
        
        onChanged();
        return getDescriptorSetFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder() {
        if (descriptorSetBuilder_ != null) {
          return descriptorSetBuilder_.getMessageOrBuilder();
        } else {
          return descriptorSet_ == null ?
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
        }
      }
      /**
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> 
          getDescriptorSetFieldBuilder() {
        if (descriptorSetBuilder_ == null) {
          descriptorSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder>(
                  getDescriptorSet(),
                  getParentForChildren(),
                  isClean());
          descriptorSet_ = null;
        }
        return descriptorSetBuilder_;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes message = 3;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>bytes message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SelfDescribe)
    }

    // @@protoc_insertion_point(class_scope:SelfDescribe)
    private static final SelfDescribePro.SelfDescribe DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SelfDescribePro.SelfDescribe();
    }

    public static SelfDescribePro.SelfDescribe getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SelfDescribe>
        PARSER = new com.google.protobuf.AbstractParser<SelfDescribe>() {
      @java.lang.Override
      public SelfDescribe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SelfDescribe(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SelfDescribe> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SelfDescribe> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SelfDescribePro.SelfDescribe getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SelfDescribe_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SelfDescribe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023self_describe.proto\032 google/protobuf/d" +
      "escriptor.proto\"i\n\014SelfDescribe\022:\n\016descr" +
      "iptor_set\030\001 \001(\0132\".google.protobuf.FileDe" +
      "scriptorSet\022\014\n\004name\030\002 \001(\t\022\017\n\007message\030\003 \001" +
      "(\014B\021B\017SelfDescribeProb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_SelfDescribe_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SelfDescribe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SelfDescribe_descriptor,
        new java.lang.String[] { "DescriptorSet", "Name", "Message", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
